### ISSUE TITLE
`execute_atom` does not return results

### ISSUE THREAD

**Issue by ntoxeg** [singnet/opencog-workshops#1]
I set up a Docker container according to the instructions and went through the Pattern Matcher notebook. Parts that invoke `execute_atom` on `BindLink`s don't return anything. Using the `satisfying_set` procedure got me a `SetLink` with proper results though.

**Comment by noskill** [comment]
I just checked notebooks from https://github.com/singnet/opencog-workshops/tree/master/intro-singnet and https://github.com/singnet/opencog-workshops/tree/master/tokyo-20190405

execute_atom seems to work, let me know if the issue still is reproducible
